[workspace]

members = [
    "codegen",
    "proc_blocks/*",
    "rune",
    "runefile-parser",
    "runic-types",
    "runic-transform",
    "syntax",
    "xtask"
]

exclude = [
    "examples/sine/rune-rs",
    "examples/boilerplate",
    "examples/gesture"
]
default-members = ["rune"]
