[package]
name = "rune"
version = "0.1.0"
authors = ["Kartik Thakore <kartik@thakore.ai>", "Akshay Sharma <akshay@sharma.ai>"]
edition = "2018"
license = "Apache 2.0"
keywords = ["tinyml", "container", "pest"]


[dependencies]
structopt = { version = "0.3", default-features = false }
runefile-parser = { git = "ssh://git@github.com/hotg-ai/runefile-parser" }
pest = "2.1"
pest_derive = "2.1"
cargo = "0.47.0"
