[package]
name = "rune"
version = "0.2.0"
authors = ["Kartik Thakore <kartik@thakore.ai>", "Akshay Sharma <akshay@sharma.ai>"]
edition = "2018"
license = "Apache 2.0"
keywords = ["tinyml", "container", "pest"]


[dependencies]
#runefile-parser = { git = "ssh://git@github.com/hotg-ai/runefile-parser" }
runefile-parser = { path = "../runefile-parser" }
#runic-os = { git = "ssh://git@github.com/hotg-ai/runic-os" }
runic-os = { path = "../runic-os" }
runic-types = { git = "ssh://git@github.com/hotg-ai/runic-types-pb" }
pest = "2.1"
pest_derive = "2.1"
cargo = "0.47.0"
clap = "2.33.3"
env_logger = "0.8.1"
log = "0.4.11"
rand = "0.7.3"

