[build.env]
passthrough = [
    "CROSS_CONTAINER_UID",
    "CROSS_CONTAINER_GID"
]

[target.aarch64-unknown-linux-gnu]
image = "tinyverseml/runecoral-cross-linux-aarch64"

[target.x86_64-unknown-linux-gnu]
image = "tinyverseml/runecoral-cross-linux-x86_64"

[target.aarch64-linux-android]
image = "tinyverseml/runecoral-cross-android-aarch64"

[target.x86_64-linux-android]
image = "tinyverseml/runecoral-cross-android-x86_64"

[target.armv7-unknown-linux-gnueabi]
image = "tinyverseml/runecoral-cross-linux-armv7"
