[package]
name = "normalize"
version = "0.8.0"
authors = ["The Rune Developers <developers@hotg.ai>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = "^0.8.0"
