[package]
name = "most_confident_indices"
version = "0.4.0"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotg-rune-proc-blocks = { path = "../proc-blocks", version = "0.4.0-dev" }
hotg-rune-core = { path = "../../crates/rune-core", version = "0.4.0-dev" }
