[package]
name = "noise-reduction"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runic-types = { path = "../../runic-types" }

[dev-dependencies]
pretty_assertions = "0.7.2"
